name: CocoDiag CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build debug apk
        run: ./gradlew assembleDebug
      - name: Run unit tests
        run: ./gradlew testDebug
      - name: Lint code
        run: ./gradlew lintDebug